// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projet.Models;

namespace projet.Migrations
{
    [DbContext(typeof(PrjContext))]
    [Migration("20200509180005_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projet.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("mdp")
                        .IsRequired();

                    b.Property<string>("nom")
                        .IsRequired();

                    b.Property<string>("photo")
                        .IsRequired();

                    b.Property<string>("prenom")
                        .IsRequired();

                    b.Property<string>("username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("projet.Models.chapitre", b =>
                {
                    b.Property<int>("id_chap")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contenu")
                        .IsRequired();

                    b.Property<string>("date_depot")
                        .IsRequired();

                    b.Property<int?>("id_mod");

                    b.Property<string>("responsable")
                        .IsRequired();

                    b.Property<string>("type")
                        .IsRequired();

                    b.HasKey("id_chap");

                    b.HasIndex("id_mod");

                    b.ToTable("chapitres");
                });

            modelBuilder.Entity("projet.Models.Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("mdp")
                        .IsRequired();

                    b.Property<string>("nom")
                        .IsRequired();

                    b.Property<string>("photo")
                        .IsRequired();

                    b.Property<string>("prenom")
                        .IsRequired();

                    b.Property<string>("telephone")
                        .IsRequired();

                    b.Property<string>("username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("projet.Models.Filiere", b =>
                {
                    b.Property<int>("id_fil")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nom_fil")
                        .IsRequired();

                    b.HasKey("id_fil");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("projet.Models.Module", b =>
                {
                    b.Property<int>("id_mod")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Id");

                    b.Property<int?>("id_niv");

                    b.Property<string>("nom_mod")
                        .IsRequired();

                    b.HasKey("id_mod");

                    b.HasIndex("Id");

                    b.HasIndex("id_niv");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("projet.Models.niveau", b =>
                {
                    b.Property<int>("id_niv")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("id_fil");

                    b.Property<string>("nom_niv")
                        .IsRequired();

                    b.HasKey("id_niv");

                    b.HasIndex("id_fil");

                    b.ToTable("Niveaus");
                });

            modelBuilder.Entity("projet.Models.chapitre", b =>
                {
                    b.HasOne("projet.Models.Module", "Module")
                        .WithMany("chapitres")
                        .HasForeignKey("id_mod");
                });

            modelBuilder.Entity("projet.Models.Module", b =>
                {
                    b.HasOne("projet.Models.Enseignant", "Enseignant")
                        .WithMany("Modules")
                        .HasForeignKey("Id");

                    b.HasOne("projet.Models.niveau", "niveau")
                        .WithMany("Modules")
                        .HasForeignKey("id_niv");
                });

            modelBuilder.Entity("projet.Models.niveau", b =>
                {
                    b.HasOne("projet.Models.Filiere", "Filiere")
                        .WithMany("Niveaus")
                        .HasForeignKey("id_fil");
                });
#pragma warning restore 612, 618
        }
    }
}
